### ISSUE TITLE
Deployment pipeline 

### ISSUE THREAD

**Issue by takahi-i** [walter-cd/walter#103]
I would like to have a deployment (release) pipeline. 

```
service:
    type: github
    token: ADD_YOUR_KEY
    repo: YOUR_REPOSITORY_NAME
    from: YOUR_ACCOUNT_OR_GROUP_NAME
    update: UPDATE_FILE_NAME

deploy:
    - name: release tag
      command:  code: |
          export RELEASE_TAG=$(curl https://api.github.com/repos/walter-cd/walter/tags | jq -r ".[] | select(.commit.sha == \"${WERCKER_GIT_COMMIT}\") | .name")
    - name: releaes windows
      type: github-release
      tag: $RELEASE_TAG
      file: snapshot/walter_windows_386.tar.gz 
```
