### ISSUE TITLE
Parallel builds support

### ISSUE THREAD

**Issue by mizzy** [walter-cd/walter#107]
Walter supports parallel execution by `run_after`, but I'd like to execute main builds in parallel.

How about this YAML format to support this feature ?

```yaml
pipeline:
  - name: 
    type: command
    command: echo "hello, world"
  - name: command_stage_2
    type: command
    command: echo "hello, world, command_stage_2"
  - name: command_stage_3
    type: command
    command: echo "hello, world, command_stage_3"
  - name: parallel builds
    type: parallel
    builds:
      - name: parallel build 1
        type: command
        command: parallel_command_1
      - name: parallel build 2
        type: command
        command: parallel_command_2
      - name: parallel build 3
        type: command
        command: parallel_command_3
```

Please check it.
