### ISSUE TITLE
Select trunk branch in VCS repository

### ISSUE THREAD

**Issue by takahi-i** [walter-cd/walter#110]
I would like to specify the master branch which Walter checks. Currently Walter assumes that the trunk branch name is **master**.

The configuration would be as follows.

```
service:
  type: github
  token: ADD_YOUR_KEY
  repo: YOUR_REPOSITORY_NAME
  from: YOUR_ACCOUNT_OR_GROUP_NAME
  update: UPDATE_FILE_NAME
  trunck: my-master-branch
```
