### ISSUE TITLE
Execution stages in specified (remote) machines

### ISSUE THREAD

**Issue by takahi-i** [walter-cd/walter#12]
The following is the sample of the remote config.

```
stage: testing-db
     type: serverspec
        conf: hoge/serverspec_db.spec
     target:
        - db-host3.localdomain
         - db-host4.localdomain
```
