### ISSUE TITLE
walter 1.3.0 is degraded in messenger

### ISSUE THREAD

**Issue by cynipe** [walter-cd/walter#139]
Colorize and suppress option in messenger is seems like degraded in v1.3.0.

You could reproduce with following codes:

reproduce.sh:
```bash
#!/bin/bash
set -e

download_walter() {
  local version=$1
  curl -sSL https://github.com/walter-cd/walter/releases/download/v${version}/walter_${version}_darwin_amd64.zip | tar xz \
    && mv walter_darwin_amd64 walter-${version} \
    && rm -rf walter_darwin_amd64
}
run() {
  local version=$1
  walter-${version}/walter -v
  walter-${version}/walter -c walter.yml
}

[ -d 'walter-1.2.0' ] || download_walter 1.2.0
[ -d 'walter-1.3.0' ] || download_walter 1.3.0

run 1.2.0
run 1.3.0
```

walter.yml
```yaml
messenger:
  type: slack
  channel: "#channel"
  username: user
  url: "webhook-url"
  suppress:
    - stdout
    - stderr

pipeline:
  - name: hoge
    type: command
    command: echo "hello, world, hoge"
    report_full_output: true
  - name: foo
    type: command
    command: echo "hello, world, foo"
    report_full_output: true
  - name: bar
    type: command
    command: echo "hello, world, bar"
    report_full_output: true
```

## Result

![image](https://cloud.githubusercontent.com/assets/242079/10968160/b02e3a74-8402-11e5-9642-8c6104781475.png)
