### ISSUE TITLE
Change config format

### ISSUE THREAD

**Issue by takahi-i** [walter-cd/walter#15]
The new configuration format represents the dependencies with the level of indentations.
The following is a sample of new format.

```
 global:
     dummyOpt: true

pipeline:
- command_stage_1:
    stage_type: command
    command: echo "hello, world"
    -  command_stage_2:
            stage_type: command
            command: echo "hello, world, command_stage_2"
- command_stage_3:
    stage_type: command
    command: echo "hello, world, command_stage_3"
```
