### ISSUE TITLE
Specify user who runs command

### ISSUE THREAD

**Issue by takahi-i** [walter-cd/walter#40]
Specifying the user to run command in the configuration file would be useful especially the higher level stages such as Ansible or Capistrano.

The configuration would be the above conf.

```
 pipeline:
    - stage_name: command_stage_1
       stage_type: command
       command: echo "hello, world"
       user: takahi-i
```
