### ISSUE TITLE
Separate control and statement

### ISSUE THREAD

**Issue by ainoya** [walter-cd/walter#50]
Now we describe control and statement all togather in `pipeline.yml`,  but it makes the pipeline complex, less readable.

For example:
```
pipeline:
  -  stage_name: check required command
     stage_type: command
     command: |
       for d in $(echo "docker mvn git bundle");do
         command -v $d >/dev/null 2>&1 || 
         { echo "Pipeline requires command $d but it's not installed.  Aborting." >&2; exit 1;}
       done
  -  stage_name: build docker image
     stage_type: command
     command: cd base && sudo docker build -t base .
     run_after:
       -  stage_name: run docker container
          stage_type: command
          command: cd base && ./run.sh node01
          run_after:
            -  stage_name: apply ansible playbook
               stage_type: command
               command: |
                  cd vendor &&
                  git clone https://github.com/ainoya/ansible-examples.git &&
                  cd ansible-examples/tomcat-standalone &&
                  TARGET=$(sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' node01) &&
                  sed -ie "s/{{ host }}/${TARGET}/g" hosts &&
                  export PYTHONUNBUFFERED=1 &&
                  export ANSIBLE_HOST_KEY_CHECKING=False
                  ansible-playbook -i hosts site.yml 2>&1
               run_after:
                 -  stage_name: validate container with serverspec
                    stage_type: command
                    command: sleep 10 && bundle exec rake spec 2>&1
       -  stage_name: maven test app
          stage_type: command
          command: |
            cd vendor &&
            git clone https://github.com/ainoya/spring-petclinic.git &&
            cd spring-petclinic &&
            mvn test 2>&1
```

To improve this readability problem, I suggest that allowing describe control and statement separately in `pipeline.yml`.

For example:

```
statements:
  statement_1:
    type: command
    command: echo "1"
  statement_2:
    type: command
    command: echo "1"
  statement_3:
    type: command
    command: echo "1"
### 
pipeline:
  -  stage_name: stage_1
     statement: statement_1.
     run_after:
       -  stage_name:  stage_2
          statement: statement_2
       -  stage_name:  stage_3
          statement: statement_3
```
