### ISSUE TITLE
Can I take settings from environment variables?

### ISSUE THREAD

**Issue by sawanoboly** [walter-cd/walter#67]
Hi, I'm using the walter to CI (localmachine, CiecleCI, Jenkins , etc...).

I would like to override pipline.yml by project specific values from environment variables.

For example, like below.

```
messenger:
  type: slack
  channel: {{SLACK_CHANNEL}}
  url: {{SLACK_HOOK_URL}}
...
```
