### ISSUE TITLE
GitHub 連携について

### ISSUE THREAD

**Issue by mizzy** [walter-cd/walter#69]
## GitHub 連携の概要
- 新しいコミットを検知してビルドを実行
  - 新しいコミットは [Commits API](https://developer.github.com/v3/repos/commits/) で取得
  - プルリクエストに紐づくコミットは [Pull Requests API](https://developer.github.com/v3/pulls/) から取得する必要があるかも（要検証）
- ビルド結果を [Statuses API](https://developer.github.com/v3/repos/statuses/) に通知
- GitHub Enterprise にも対応
## 懸念事項や補足など
- cron などで定期的に新しいコミットを取得するには、前回実行時のタイムスタンプをどこかに保持する必要がある
  - Web Hook を利用する場合は必要がないが、Web Hook の実装が必要
- ビルドジョブのキューイング
  - コミットが複数取得されるケースや、ビルドの最中に新たなコミットが発生するケースもあるため、キューイングが必要そう
  - あまり大げさな仕組みにしたくないので、SQLite あたりで実装？
  - [SQLite によるジョブキュー実装サンプル](http://flask.pocoo.org/snippets/88/Python)
## 設定例

以下のような感じで設定できると良さそう。

``` yaml
pipeline:
  - stage_name: GitHub
    github_access_token: {{ GITHUB_ACCESS_TOKEN }}
    github_api_url: https://github-enterprise.example.jp/api/v3/
```
- github_api_url は、GitHub Enterprise の場合に設定
- リポジトリ名などは、git remote -v などから拾う
- アクセストークンをコマンドラインで取得できるようにすると便利そう
## その他参考になりそうなところ
- [Python - GitHub APIのステータス表示で遊ぼう - Qiita](http://qiita.com/bonon0/items/ef383581c2ba871ede90)
- [google/go-github](https://github.com/google/go-github)
- [Drone の GitHub 連携コード](https://github.com/drone/drone/tree/master/plugin/remote/github)
  - golang から GitHub API にアクセスする際の参考になりそう
  - ただし、上記の google/go-github ではなく、[drone/go-github](https://github.com/drone/go-github) を使っている模様。
