### ISSUE TITLE
cwd support for command type

### ISSUE THREAD

**Issue by mizzy** [walter-cd/walter#82]
[Wercker](http://wercker.com/) supports `cwd` for setting current working direcotry when running command like this.

```yaml
build:
  steps:
    - script:
        name: Run command
        code: command foo bar
        cwd: $HOME
```

I need this feature with walter.
